src/DoctrineAuditBundle/Controller/AuditController.php
src/DoctrineAuditBundle/Resources/views/Audit/audited_entities.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/entity_audit_details.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/entity_history.html.twig

This makes the template compatible with projects disabling the Templating
component in recent Symfony versions and allow overwrite layout template

Use native Twig references for templates

---

src/DoctrineAuditBundle/Controller/AuditController.php

The "Symfony\Bundle\FrameworkBundle\Controller\Controller" class is deprecated since Symfony 4.2, use Symfony\Bundle\FrameworkBundle\Controller\AbstractController instead.

Support Symfony 4.2+

---

src/DoctrineAuditBundle/User/TokenStorageUserProvider.php

if user has no 'SwitchUserRole' role the impersonatorUser variable is not set what trigger the error

impersonatorUser should be defined

---

README.md
src/DoctrineAuditBundle/Controller/AuditController.php
src/DoctrineAuditBundle/Helper/AuditHelper.php
src/DoctrineAuditBundle/Reader/AuditEntry.php
src/DoctrineAuditBundle/Reader/AuditReader.php
tests/DoctrineAuditBundle/Fixtures/Issues/Locale.php
tests/DoctrineAuditBundle/Fixtures/Issues/User.php
tests/DoctrineAuditBundle/IssueTest.php
tests/DoctrineAuditBundle/Reader/AuditEntryTest.php

As of now, `AuditEntry::object_id` is a string. This allows to support auditing entities with non numeric primary key.

Non numeric primary key support

---

README.md
src/DoctrineAuditBundle/AuditConfiguration.php
src/DoctrineAuditBundle/AuditManager.php
src/DoctrineAuditBundle/DependencyInjection/Configuration.php
tests/DoctrineAuditBundle/AuditConfigurationTest.php
tests/DoctrineAuditBundle/BaseTest.php
tests/DoctrineAuditBundle/CoreTest.php
tests/DoctrineAuditBundle/DependencyInjection/DHDoctrineAuditExtensionTest.php
tests/DoctrineAuditBundle/Helper/AuditHelperTest.php

In certain scenarios, it is useful for the audit `created_at` timestamp to be in the same timezone as the users using the application. In our application this prevents confusion when viewing audits and simplifies the view logic.
This pull request allows the developer to configure a custom timezone in YAML which audits are saved based on. If the configuration isn't present it replicates the existing behaviour of defaulting to UTC.

Allow timezone to be configured in package configuration

---

src/DoctrineAuditBundle/DBAL/AuditLoggerChain.php
src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
src/DoctrineAuditBundle/Helper/AuditHelper.php

See Issue 70. LoggerChains are nested inside each other and when Doctrine calls startQuery on the EntityManager's SQLLogger, the LoggerChains will create call stacks for each nest. If xdebug is enabled, once the call stack reaches the "max_nesting_level", an Exception will be thrown. 
This code flattens the EntityManager's SQLLogger by detecting if it is already a LoggerChain and if so only appending the AuditLogger created.

Nested LoggerChains causing big call stack 

---

CHANGELOG.md
README.md
src/DoctrineAuditBundle/AuditManager.php
src/DoctrineAuditBundle/Helper/AuditHelper.php
src/DoctrineAuditBundle/Reader/AuditReader.php
tests/DoctrineAuditBundle/Fixtures/Core/Vehicle.php
tests/DoctrineAuditBundle/IssueTest.php

Although STI was supported, there was no way to get audits about a specific child entity, `AuditReader::getAudits()` was getting audits of both the root entity and of its children.
This PR addresses this limitation.

Single table inheritance support

---

CHANGELOG.md
README.md
src/DoctrineAuditBundle/EventSubscriber/CreateSchemaListener.php
src/DoctrineAuditBundle/Resources/config/services.yaml

The purpose of this PR is to bring back the `CreateSchemaListener` for single database setup only. This makes `doctrine:schema:update`, `doctrine:migrations:diff` and consequently `make:migration` take audit tables into consideration. This also should fix #91

Bring back the schema listener and restrict its usage to single database setups

---

composer.json
src/DoctrineAuditBundle/Annotation/AnnotationLoader.php
src/DoctrineAuditBundle/Annotation/Auditable.php
src/DoctrineAuditBundle/Annotation/Ignore.php
src/DoctrineAuditBundle/AuditConfiguration.php
src/DoctrineAuditBundle/Resources/config/services.yaml
tests/DoctrineAuditBundle/AuditConfigurationTest.php
tests/DoctrineAuditBundle/BaseTest.php
tests/DoctrineAuditBundle/CoreTest.php
tests/DoctrineAuditBundle/DHDoctrineAuditBundleTest.php
tests/DoctrineAuditBundle/Helper/AuditHelperTest.php
tests/DoctrineAuditBundle/Manager/AuditTransactionTest.php

Initial annotation support:
- Auditable: define an entity as auditable (supports `enabled` option)
- Ignore: exclude a property from auditing

Annotation support

---

src/DoctrineAuditBundle/Resources/views/Audit/helper.html.twig

when unassigning a relation it saves it as `target: null` but `is defined` only checks if the variable exists and will return true even when the variable is null

[BUG] make sure target is defined and not null

---

composer.json
doc/50-audits-cleanup.md

otherwise `audit:clean` and `audit:schema:update` can’t be executed

symfony/lock required in non-dev

---

phpstan.neon
src/DoctrineAuditBundle/Manager/AuditManager.php
src/DoctrineAuditBundle/Reader/AuditReader.php
tests/DoctrineAuditBundle/Reader/AuditReaderTest.php

This should address #123 feature request (filtering using multiple filters at once).

Allow multiple filters in `AuditReader::filterBy()`

---

src/DoctrineAuditBundle/Resources/config/services.yaml
tests/DoctrineAuditBundle/DependencyInjection/DHDoctrineAuditExtensionTest.php

Makes sure the `onFlush` subscriber executes first by setting a very high priority.
This lets it can capture all entity mutations originating from other listeners (should fix #122)

Ensures DoctrineSubscriber is registered first

---

doc/21-audit-configuration.md

4228267 renamed the "roles" attribute of Security annotation to "view". This PR fixes the corresponding documentation accordingly.

Fix doc related to 4228267

---

src/DoctrineAuditBundle/Reader/Paginator.php

Specify parameter types when cloning a query builder in Paginator (fixes #150)

Bug fix in Paginator when filters are used

---

composer.json
src/DoctrineAuditBundle/Resources/config/translations.yaml
src/DoctrineAuditBundle/Resources/views/Audit/audits.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/entity_history.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/entry.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/helpers/pager.html.twig
src/DoctrineAuditBundle/Resources/views/Audit/transaction.html.twig
src/DoctrineAuditBundle/translations/messages.de.yaml
src/DoctrineAuditBundle/translations/messages.en.yaml
src/DoctrineAuditBundle/translations/messages.es.yaml
src/DoctrineAuditBundle/translations/messages.fr.yaml
src/DoctrineAuditBundle/translations/messages.it.yaml

Related to #126 
Implemented symfony/translations
added 5 languages [english, italian, french, spanish, german]
- Italian has been traslated by me
- For french, spanish, german I used Google Translate

Localization: add translations for twig templates

---

src/DoctrineAuditBundle/AuditConfiguration.php
src/DoctrineAuditBundle/DHDoctrineAuditBundle.php
src/DoctrineAuditBundle/DependencyInjection/Compiler/DisableAuditViewerPass.php
src/DoctrineAuditBundle/DependencyInjection/Configuration.php
src/DoctrineAuditBundle/Resources/config/routes.yaml
src/DoctrineAuditBundle/Resources/config/services.yaml
src/DoctrineAuditBundle/Routing/DoctrineAuditRoutingLoader.php
tests/DoctrineAuditBundle/AuditConfigurationTest.php
tests/DoctrineAuditBundle/BaseTest.php
tests/DoctrineAuditBundle/CoreTest.php
tests/DoctrineAuditBundle/DHDoctrineAuditBundleTest.php
tests/DoctrineAuditBundle/DependencyInjection/Compiler/DisableAuditControllerPassTest.php
tests/DoctrineAuditBundle/DependencyInjection/DHDoctrineAuditExtensionTest.php
tests/DoctrineAuditBundle/Helper/AuditHelperTest.php
tests/DoctrineAuditBundle/Manager/AuditTransactionTest.php

@DamienHarper & @maxhelias Hi all, I implemented a solution to programmatically disable AuditController::class,
this way a new configuration parameter could be set to *false* and that controller and its routes won't be available.
The use case to cover is a use case in which the library is used to store informatin on the persistence layer but they will be available in a different way to the user, for example through API.
The controller routes won't be exposed to any environment.
The parameter is:
- ```enable_audit_controller```
and has been added to the Configuration.php file.
- default value is *true*
reference issue #153

added flag parameter for enabling AuditController

---

src/DoctrineAuditBundle/Command/CleanAuditLogsCommand.php
tests/DoctrineAuditBundle/Command/CleanAuditLogsCommandTest.php

Added possibility to define an ISO 8601 date interval to be subtracted from current date in the clean audit logs command

Cleanup command accepts an ISO 8601 date interval

---

src/DoctrineAuditBundle/Manager/AuditManager.php

When using `get_class` you sometimes get the FQDN from the proxy of the entity (`Proxies\__CG__\Foo\Bar`). 
When you obtain the class name from `ClassMetadata` you always get the correct one.

Changed how the entity FQDN is obtained

---

src/DoctrineAuditBundle/Helper/AuditHelper.php
src/DoctrineAuditBundle/Manager/AuditManager.php

Leverage `DoctrineHelper::getRealClassName()` to avoid proxy references in audit entries.
This PR should fix #177

Avoid proxy references in audit entries

---

src/DoctrineAuditBundle/Resources/config/services.yaml
tests/DoctrineAuditBundle/DependencyInjection/DHDoctrineAuditExtensionTest.php

Specifying the connection forces the user to override it in configuration if they don't use default as the name of their connection. Symfony already provides a configurable setting for the name of the connection as "doctrine.dbal.default_connection", and this will be used if one isn't specified in the service. This value defaults to default if not specified.

Don't specify the doctrine connection in services.yml

---

src/DoctrineAuditBundle/Transaction/AuditTrait.php

I've some problem with fixtures loading in a project after added this bundle.
Before this update, when I try to retrieve an entity by reference I've an empty Entity.
```php
$post1 = $referenceRepository->getReference('post_1');
$post1->getId();
```
`getId()` returns null
I've noticed that before to call `initializeObject($entity)` I've an object with all fields filled and after the call all fields are null.  With this update I've resolved the problem

Check if  object is initialized before call initializeObject

---

src/DoctrineAuditBundle/Resources/views/Audit/entry.html.twig

Looks like template had a static date set by accident. Here's a fix.
I kept date formatting similar to what element contains.

Template static datetime fix

---

src/DoctrineAuditBundle/User/TokenStorageUserProvider.php
tests/DoctrineAuditBundle/CoreTest.php
tests/DoctrineAuditBundle/User/TokenStorageUserProviderTest.php

Since `symfony/security-core 5.1` `ROLE_PREVIOUS_ADMIN` is deprecated and should change to IS_IMPERSONATOR instead.
I created a check for the current constant of it: `'\Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter::IS_IMPERSONATOR` and change the impersonating attribute accordingly.
I applied the same logic to tests
Fixes #206

Remove the ROLE_PREVIOUS_ADMIN deprecation warning from Symfony 5.1

---

src/DoctrineAuditBundle/Event/AuditSubscriber.php

Allows to  use bundle prior to having any *_audit table created. Solved https://github.com/DamienHarper/auditor-bundle/issues/204

Handle TableNotFoundException.

---

src/Resources/views/Audit/entity_history.html.twig

Bug in pagination, the pager prints the routes like 
http://my-domain.com/my-project/public/audit/App/Entity/User?page=7
instead
http://my-domain.com/my-project/public/audit/App-Entity-User?page=7

Bug in the pager that makes the pagination pages unreachable

---

src/DependencyInjection/Configuration.php

followup to https://github.com/DamienHarper/auditor-bundle/commit/a155712f7dbbf73f9c74c52ba6b1a665215abd3a that changed the behaviour but not the comment

Update Configuration comment as viewer is now disabled by default

---

src/Event/ViewerEventSubscriber.php

Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "DH\AuditorBundle\Event\ViewerEventSubscriber" now to avoid errors or add an explicit @return annotation to suppress this message.

Prevent deprecation notice when using Symfony 5.4.2

---

src/User/UserProvider.php

Since the DH\Auditor\User\User constructor requires the first argument to be string or null. I have an UserInterface implementation where $tokenUser->getId() returns int, so there will be an exception. The check is on DH\AuditorBundle\User\UserProvider: if (method_exists($tokenUser, 'getId')) { $identifier = $tokenUser->getId(); }. To be safe, it is better to cast the getId() value to string, IMHO.

Cast to string the user identifier

---

src/Event/ConsoleEventSubscriber.php
src/Resources/config/services.yaml
src/User/ConsoleUserProvider.php
tests/App/Command/CreatePostCommand.php
tests/App/Kernel.php
tests/App/config/services.yaml
tests/Console/ConsoleUserProviderTest.php
tests/DHAuditorBundleTest.php

* Adds a provider and listeners to view which console command was responsible for certain actions.
Fixes #267

Add a console user provider

---

.gitattributes

/tools and rector.php not need to be in project's vendor

Ignore extra files from vendor

---

src/Resources/config/services.yaml
tests/App/Kernel.php
tests/App/config/packages/sf6/framework.yaml
tests/DHAuditorBundleTest.php

Fixed `doctrine-bundle` (6.3+) deprecations

Deprecation fixes

---

src/Resources/views/layout.html.twig

Wrapped the title, navbar and the breadcrums in blocks so you could override them without having to override the whole file. Also removed some unused code and added the current locale to the language attribute of the html-element.

title, navbar and breadcrums in block tags

---

.github/workflows/ci-4.x.yml
.github/workflows/ci-5.x.yml
src/Controller/ViewerController.php
src/Resources/config/services.yaml

After upgrading to Symfony 6.4, the ViewerController stopped working while throwing the following exception:
```
Uncaught PHP Exception LogicException: "You cannot use the "render" method if the Twig Bundle is not available. Try running "composer require symfony/twig-bundle"." at AbstractController.php line 435
```
Upon investigation with @mvhirsch, we discovered that the service_container injected into the controller lacked the twig service. However, this shouldn't have been a problem since twig was injected directly via arguments. The root cause turned out to be the use of `AbstractController::render()` method, which attempts to access twig from the service container, instead of the intended `ViewerController::renderView()`.
Additionally, I've realized that there is no necessity to …

Fix: `ViewerController`

---

src/Controller/ViewerController.php

Follows https://github.com/DamienHarper/auditor-bundle/pull/379#issuecomment-1865605165
Afterwards we can make it final final in `master` 👍 
cc @mvhirsch

Make `ViewerController` final

---

composer.json

Remove useless `ext-json` requirement from `composer.json` 
@see https://php.watch/versions/8.0/ext-json

Useless `ext-json` requirement

---

src/Resources/views/Audit/helpers/helper.html.twig

Hello,
This PR removes the call to the `spaceless` Twig filter that has been deprecated.
See https://twig.symfony.com/doc/3.x/filters/spaceless.html

Fix Twig spaceless filter deprecation
