- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
- src/DoctrineAuditBundle/Resources/views/Audit/entity_audit_details.html.twig
- and + does not allows to use plain sql to fetch and search data with JSON_* functions
> AuditSubscriber diff method use old|new vs -|+

- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
- src/DoctrineAuditBundle/Resources/views/Audit/entity_audit_details.html.twig
> Strict comparisons

- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
```
Notice: Undefined index: fieldName
```
Issue occurred on insert operation on entity with embedded mapping.
> Fix listener on embedded field

- README.md
- src/DoctrineAuditBundle/AuditConfiguration.php
- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
- src/DoctrineAuditBundle/Resources/config/services.yaml
- src/DoctrineAuditBundle/User/TokenStorageUserProvider.php
- src/DoctrineAuditBundle/User/User.php
- src/DoctrineAuditBundle/User/UserInterface.php
- src/DoctrineAuditBundle/User/UserProviderInterface.php
> Custom user provider

- src/DoctrineAuditBundle/AuditReader.php
- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
This patch is works for me. Please check if i missed anything.
> Add schema support

- src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php
- src/DoctrineAuditBundle/Resources/config/services.yaml
- src/DoctrineAuditBundle/User/TokenStorageUserProvider.php
Check for `ROLE_PREVIOUS_ADMIN` role/flag and include the impersonator in the username column.
> Track impersonator

- phpunit.xml.dist
- src/DoctrineAuditBundle/AuditManager.php
- src/DoctrineAuditBundle/Command/CleanAuditLogsCommand.php
- src/DoctrineAuditBundle/Command/UpdateSchemaCommand.php
- src/DoctrineAuditBundle/EventSubscriber/CreateSchemaListener.php
- src/DoctrineAuditBundle/Exception/UpdateException.php
- src/DoctrineAuditBundle/Helper/AuditHelper.php
- src/DoctrineAuditBundle/Helper/UpdateHelper.php
- src/DoctrineAuditBundle/Resources/config/services.yaml
- tests/DoctrineAuditBundle/AuditManagerTest.php
- tests/DoctrineAuditBundle/BaseTest.php
- tests/DoctrineAuditBundle/Command/CleanAuditLogsCommandTest.php
- tests/DoctrineAuditBundle/DependencyInjection/DHDoctrineAuditExtensionTest.php
- tests/DoctrineAuditBundle/EventSubscriber/AuditSubscriberTest.php
- tests/DoctrineAuditBundle/Fixtures/Core/Vehicle.php
- tests/DoctrineAuditBundle/Fixtures/Issues/CoreCase.php
- tests/DoctrineAuditBundle/Helper/AuditHelperTest.php
- tests/DoctrineAuditBundle/Helper/UpdateHelperTest.php
- tests/DoctrineAuditBundle/IssueTest.php
- tests/DoctrineAuditBundle/Reader/AuditReaderTest.php
- tests/travis/mysql.travis.xml
- tests/travis/pgsql.travis.xml
- tests/travis/sqlite.travis.xml
Provide a way to make it easier to apply migrations to audit tables in case their structure change over time in order to bring in new features.
> Audit updater

- src/DoctrineAuditBundle/AuditConfiguration.php
- src/DoctrineAuditBundle/AuditManager.php
- src/DoctrineAuditBundle/Helper/AuditHelper.php
- src/DoctrineAuditBundle/Reader/AuditEntry.php
- src/DoctrineAuditBundle/Resources/config/services.yaml
- src/DoctrineAuditBundle/Resources/views/Audit/entity_history.html.twig
- tests/DoctrineAuditBundle/AuditConfigurationTest.php
- tests/DoctrineAuditBundle/BaseTest.php
- tests/DoctrineAuditBundle/CoreTest.php
- tests/DoctrineAuditBundle/DHDoctrineAuditBundleTest.php
- tests/DoctrineAuditBundle/Helper/AuditHelperTest.php
> Add support for multiple firewalls

- composer.json
- src/DoctrineAuditBundle/Controller/AuditController.php
- src/DoctrineAuditBundle/Reader/AuditReader.php
- src/DoctrineAuditBundle/Resources/views/Audit/audits.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/entity_history.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/helper.html.twig
- src/DoctrineAuditBundle/Twig/Extension/TwigExtension.php
- tests/DoctrineAuditBundle/Reader/AuditReaderTest.php
- tests/DoctrineAuditBundle/Twig/Extension/TwigExtensionTest.php
- tests/README.md
Use Pagerfanta to paginate timeline
> Pagination

- src/DoctrineAuditBundle/Controller/AuditController.php
- src/DoctrineAuditBundle/Helper/AuditHelper.php
- src/DoctrineAuditBundle/Resources/views/Audit/audits.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/entity_history.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/entity_history_entry.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/helper.html.twig
- tests/DoctrineAuditBundle/Helper/AuditHelperTest.php
Fix a Windows compatibility issue regarding URLs including namespaced entity class name (so backslashes) (#62)
> Fix for Windows URL issue

- composer.json
- src/DoctrineAuditBundle/Resources/views/Audit/bootstrap.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/helper.html.twig
https://twig.symfony.com/doc/2.x/deprecated.html#tags
> Replace deprecated spaceless tag to filter apply

- README.md
- src/DoctrineAuditBundle/AuditConfiguration.php
- src/DoctrineAuditBundle/AuditManager.php
- src/DoctrineAuditBundle/Reader/AuditReader.php
- tests/DoctrineAuditBundle/AuditConfigurationTest.php
- tests/DoctrineAuditBundle/BaseTest.php
- tests/DoctrineAuditBundle/CoreTest.php
- tests/DoctrineAuditBundle/EventSubscriber/AuditSubscriberTest.php
Although after last changes it is possible to save audits in custom storage, it was not possible to show it in administration panel. This pull request is changing it.
> Custom em in reader

- src/DoctrineAuditBundle/Helper/AuditHelper.php
- src/DoctrineAuditBundle/User/User.php
- src/DoctrineAuditBundle/User/UserInterface.php
- tests/DoctrineAuditBundle/Helper/UpdateHelperTest.php
- tests/DoctrineAuditBundle/User/TokenStorageUserProviderTest.php
- tests/DoctrineAuditBundle/User/UserTest.php
Pull request for allow use string uuid instead int.
I try to solve this #66 
In local I believe that it's working fine but I doesn't know all the implications that it could to cause. Could you @DamienHarper check it out?
> Change Id int to string 

- .php_cs
- tests/DoctrineAuditBundle/AuditConfigurationTest.php
- Updated rules
- composer shortcut
- A few files excluded
> PHP-CS-Fixer

- composer.json
> Updated twig dependencies

- tests/DoctrineAuditBundle/Command/CleanAuditLogsCommandTest.php
- tests/DoctrineAuditBundle/Command/UpdateSchemaCommandTest.php
Fixes the return type of a method in a test class that causes phpstan to raise a warning.
> Solves phpstan raising a warning

- composer.json
- phpstan.neon
- src/DoctrineAuditBundle/Annotation/AnnotationLoader.php
- src/DoctrineAuditBundle/Annotation/Security.php
- src/DoctrineAuditBundle/AuditConfiguration.php
- src/DoctrineAuditBundle/Command/CleanAuditLogsCommand.php
- src/DoctrineAuditBundle/Command/UpdateSchemaCommand.php
- src/DoctrineAuditBundle/Reader/AuditEntry.php
- src/DoctrineAuditBundle/Reader/AuditReader.php
- src/DoctrineAuditBundle/Reader/Paginator.php
- src/DoctrineAuditBundle/Twig/Extension/TwigExtension.php
- src/DoctrineAuditBundle/User/TokenStorageUserProvider.php
- src/DoctrineAuditBundle/User/User.php
- src/DoctrineAuditBundle/User/UserInterface.php
- tests/DoctrineAuditBundle/Twig/Extension/TwigExtensionTest.php
Updated PHPStan to its latest release
> PHPStan fixes

- .travis.yml
On Travis build I discover it shows now the configuration and if there are errors or warning.
I've updated the config following the config suggestions.
> Fixing travis config

- composer.json
remove `symfony/translation` duplication;
> add composer config.sort-packages; symfony/translation duplication fix

- composer.json
- src/DoctrineAuditBundle/Annotation/AnnotationLoader.php
- src/DoctrineAuditBundle/Helper/DoctrineHelper.php
- src/DoctrineAuditBundle/Twig/Extension/TwigExtension.php
- src/DoctrineAuditBundle/translations/messages.en.yaml
- tests/DoctrineAuditBundle/Event/CreateSchemaListenerTest.php
Fixed some Doctrine deprecations since doctrine/persistence 1.3.x release
> Fixed some Doctrine deprecations

- src/DoctrineAuditBundle/Resources/views/Audit/entry.html.twig
- src/DoctrineAuditBundle/Resources/views/Audit/helpers/helper.html.twig
Boolean values are properly displayed now (fix #166)
> Fixes display of boolean values in viewer

- CHANGELOG.md
- doc/00-index.md
- doc/41-accessing-audit-entries.md
- src/DoctrineAuditBundle/Command/CleanAuditLogsCommand.php
- src/DoctrineAuditBundle/Reader/AuditReader.php
- tests/DoctrineAuditBundle/Reader/AuditReaderTest.php
I fell short with the base pagination as I needed all changes between a date range with or without pagination. Also added docs for programmatic access of audits stolen from the controller. 
All tests passing, added new tests for the date ranges with and without pagination. 
Great work btw.
> Adding date range function getAuditsByDate

- phpstan.neon
- src/DoctrineAuditBundle/Event/AuditSubscriber.php
- src/DoctrineAuditBundle/Manager/AuditManager.php
- src/DoctrineAuditBundle/Reader/AuditReader.php
- tests/DoctrineAuditBundle/Reader/AuditReaderTest.php
> Add audited entity FQCN to event payload

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
> Drop PHP 7.1 support

- src/DHAuditorBundle.php
- src/DependencyInjection/Compiler/DoctrineProviderConfigurationCompilerPass.php
- src/Resources/views/layout.html.twig
- tests/DependencyInjection/Compiler/StorageConfigurationCompilerPassTest.php
> Register doctrine subscriber

- src/Event/ViewerEventSubscriber.php
> Symfony 3.4 compatibility

- src/translations/messages.et.yml
If having it is better than not having it.
entity_per_entity was difficult to grasp, but I think it will fit.
> Add estonian (ET) translation

- composer.json
> Incompatible symfony/doctrine-bridge

- src/translations/messages.nl.yaml
Added dutch translations for the auditor.
> Added dutch translations

- .php_cs
- src/DependencyInjection/Compiler/CustomConfigurationCompilerPass.php
- src/DependencyInjection/Compiler/DoctrineProviderConfigurationCompilerPass.php
> Multiple storage services

- src/Controller/ViewerController.php
- src/Resources/config/services.yaml
- tests/DHAuditorBundleTest.php
- tests/Twig/Extension/TwigExtensionTest.php
Should help for Symfony 6 compat.
> Fix deprecation notice regarding twig usage from controller. 

- .github/workflows/ci-5.x.yml
- composer.json
- rector.php
- src/DHAuditorBundle.php
- src/DependencyInjection/Compiler/CustomConfigurationCompilerPass.php
- src/Event/ViewerEventSubscriber.php
- src/Helper/UrlHelper.php
- src/Routing/RoutingAnnotationLoader.php
- src/Security/RoleChecker.php
- src/Twig/Extension/TwigExtension.php
- src/User/UserProvider.php
- tools/rector/composer.json
Bumped minimal version of PHP to 7.4
> Drop PHP 7.3 support

- .php-cs-fixer.php
- rector.php
- src/Controller/ViewerController.php
- src/DHAuditorBundle.php
- src/DependencyInjection/Compiler/AddProviderCompilerPass.php
- src/DependencyInjection/Compiler/CustomConfigurationCompilerPass.php
- src/DependencyInjection/Compiler/DoctrineProviderConfigurationCompilerPass.php
- src/DependencyInjection/DHAuditorExtension.php
- src/Event/ViewerEventSubscriber.php
- src/Helper/UrlHelper.php
- src/Routing/RoutingAnnotationLoader.php
- src/Security/RoleChecker.php
- src/Security/SecurityProvider.php
- src/Twig/Extension/TwigExtension.php
- src/User/UserProvider.php
- tests/App/Kernel.php
- tests/App/config/bootstrap.php
- tests/App/config/bundles.php
- tests/App/public/index.php
- tests/Controller/ViewerControllerTest.php
- tests/DHAuditorBundleTest.php
- tests/DependencyInjection/Compiler/AddProvidersCompilerPassTest.php
- tests/DependencyInjection/Compiler/CustomConfigurationCompilerPassTest.php
- tests/DependencyInjection/Compiler/StorageConfigurationCompilerPassTest.php
- tests/Helper/UrlHelperTest.php
- tests/Twig/Extension/TwigExtensionTest.php
- tests/bootstrap.php
Add types to properties + strict types
> Type fixes

- src/translations/auditor.nl.yaml
And improved the translation for `inserted`.
> Fixed a missing translation

- src/Resources/views/Audit/audits.html.twig
Improved the layout of the card, to ensure that the bottom part is stuck to the bottom.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Better alignment for the cards

- rector.php
- src/Controller/ViewerController.php
Rector:
- SymfonySetList::SYMFONY_54
- SymfonySetList::SYMFONY_CODE_QUALITY
- SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION
- SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES
> Drop Symfony 4.4 support

- src/Resources/config/services.yaml
- src/Security/RoleChecker.php
- src/User/UserProvider.php
> #345 Deprecation in RoleChecker and UserProvider

- composer.json
Partly closes #344
We need one more PR in `auditor` package
> Support doctrine/annotations:2.0

- src/Controller/ViewerController.php
> Make `ViewerController` real `final`

- .php-cs-fixer.dist.php
- composer.json
- phpunit.xml
- src/Resources/views/Audit/entry.html.twig
- src/Resources/views/Audit/entry_diff.html.twig
Improves how JSON changes are displayed (cf. https://github.com/DamienHarper/auditor/pull/225)
> Better JSON support

- src/translations/auditor.ru.yaml
- src/translations/auditor.uk.yaml
Add missing Russian and Ukrainian translations
> Add Russian and Ukrainian translations

- .gitattributes
> Ignore files from vendor
